---
# Check core configuration
- assert:
    that:
      - vhost_name is defined
      - vhost_root is defined
      - vhost_index is defined

# Check SSL config
- assert:
    that:
      - vhost_ssl.certificate is defined
      - vhost_ssl.private_key is defined
  when:
    - vhost_ssl != {} or vhost_redirect_http

- name: Configure Nginx virtual host
  template:
    src: vhost.conf.j2
    dest: /etc/nginx/sites-available/{{ vhost_name }}.conf
    owner: root
    group: root

- name: Enable Nginx virtual host
  file:
    src: /etc/nginx/sites-available/{{ vhost_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ vhost_name }}.conf
    state: link
  notify:
    - Reload Nginx

- name: Creates vhost directory
  file:
    path: "{{ vhost_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: Creates letsencrypt home directory
  file:
    path: /var/www/letsencrypt
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
